java:
  applicationPort: 4000
  image: 'hmctspublic.azurecr.io/my-time/api:latest'
  ingressHost: my-time-api.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: my-time
  keyVaults:
    "my-time":
      resourceGroup: my-time
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
